# Generated by Django 5.2.5 on 2025-09-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petuser',
            name='username',
        ),
        migrations.AddField(
            model_name='petuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
