# Generated by Django 5.2.5 on 2025-09-30 16:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petreview_updated_at_alter_petimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
