# Generated by Django 6.0.3 on 2026-04-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_adoption_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
