# Generated by Django 5.2.5 on 2025-08-29 13:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_created_at_pet_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
