# Generated by Django 5.2.5 on 2025-10-14 17:09

import pets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_petimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(upload_to='pets/images/', validators=[pets.validators.validate_file_size]),
        ),
    ]
