# Generated by Django 6.0.3 on 2026-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='category',
            new_name='petCategory',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='stock',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
