# Generated by Django 5.2.5 on 2025-10-19 18:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_petimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
