# Generated by Django 6.0.3 on 2026-04-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_ensure_breed_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
